### ISSUE TITLE
Hangs and never completes

### ISSUE THREAD

**Issue by AldeRoberge** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#12]
With big .SVG, it just seems like it's hanging and never completing. Would it be possible to add a loading bar?

**Comment by otuncelli** [comment]
But the plugin has a loading bar already. It has since v0.3-alpha. 

It's calculation based on object count in svg file, and not object complexity. This means if you have complex and simple objects mixed in a svg, the loading bar won't be accurate time-wise. Because rendering complex objects would take more time.

If it's hanging maybe there is another reason. If there is a problem, I need to reproduce it before i can fix it. Can you attach the problematic SVG file?
